### ISSUE TITLE
Add ability to add plugins to the custom configuration

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#10]
This is one of the main components for the service that once the user adds a plugin to the configuration we would be doing the following

- [ ] Pick up the latest version from the update center

- [ ] Cache this data as the user keeps adding plugins

**Comment by kwhetstone** [comment]
I think (think) you might be able to get away with storing most of the configuration in local memory since it can get quite large.  The cost of going to update center for each request is going to be astronomical, which I think would kill user interest in the system.  For this, let's check if we can get a lighter-weight version of the update_center.json

Just keep in mind: we'll have to work with the update_center.json in order to make it easier to support custom update centers later on in the process.  I can envision that someone might find this tool useful to spin up a config for something internally.

**Comment by kwhetstone** [comment]
The cache for the user data will be separate and you should be able to get away with more memory based storage for that since there's going to be a lot of places where that'll be used and passed around.
